package model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

@Entity // This annotation marks the class as a JPA entity, meaning it will be mapped to
		// a table in the database
@Table(name = "users") // Specifies the name of the table to which this entity will be mapped
public class User {

	// Primary key field with auto-generation of values
	@Id // Denotes this field as the primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) // This strategy indicates that the primary key will be
														// auto-generated by the database (typically for
														// auto-incremented columns)
	private int id;

	@Transient // This annotation marks the field as transient, meaning it will not be
				// persisted in the database
	private int srNo; // This field is used for serial number and is not stored in the database

	// This is a mapped column in the database, specifying that the field 'name'
	// should be mapped to a column named 'name' in the 'users' table
	@Column(name = "name", nullable = false) // 'nullable = false' means this field cannot be null in the database
	private String name;

	@Column(name = "mobile", nullable = false, unique = true) // This field is mapped to a column 'mobile' which is
																// unique and cannot be null
	private String mobile;

	@Column(name = "email", nullable = false, unique = true) // This field is mapped to a column 'email' which is unique
																// and cannot be null
	private String email;

	@Column(name = "age", nullable = false) // This field is mapped to a column 'age' and it cannot be null in the
											// database
	private int age;

	// Getters and Setters to access and modify the fields

	public int getId() {
		return id; // Returns the ID of the user
	}

	public void setId(int id) {
		this.id = id; // Sets the ID of the user
	}

	public int getSrNo() {
		return srNo; // Returns the serial number (this won't be persisted)
	}

	public void setSrNo(int srNo) {
		this.srNo = srNo; // Sets the serial number (this won't be persisted)
	}

	public String getName() {
		return name; // Returns the name of the user
	}

	public void setName(String name) {
		this.name = name; // Sets the name of the user
	}

	public String getMobile() {
		return mobile; // Returns the mobile number of the user
	}

	public void setMobile(String mobile) {
		this.mobile = mobile; // Sets the mobile number of the user
	}

	public String getEmail() {
		return email; // Returns the email address of the user
	}

	public void setEmail(String email) {
		this.email = email; // Sets the email address of the user
	}

	public int getAge() {
		return age; // Returns the age of the user
	}

	public void setAge(int age) {
		this.age = age; // Sets the age of the user
	}
}
